title = "Dalyle DevOps Inc."
baseURL = "https://new.dalyle.io/"
theme = "educenter"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "30"
summaryLength = "10"

#
# 2022-08-08 - Fix "DevOps" in blog Category Sidebar showing "Devops" without capial "o"
# https://discourse.gohugo.io/t/taxonomy-terms-with-the-original-case/13623
#
preserveTaxonomyNames = true



[params]
address = "Okotoks, Alberta, Canada"
author = "Dalyle DevOps Inc."
org_name = "Dalyle DevOps Inc."
contact_form_action = "#"
description = "Greg Stevens Experiment in trying to do things right => BETTER WEB INDUSTRY. Focusing on improving your website through all of its lifecycle, from ideazation to ongoing hosting operations and site updates. I am addicted to solving problems, let me focus on solving yours..."
email = "hello@dalyle.ca"


top_header = true



google_analitycs_id = "G-V9QYWGFZBE"




logo = "/images/logo.png"
logo_footer = "/images/logo-footer.png"
#mobile = "[(403) 295-2848](tel:+14032952848)"
#mobile = "[(587) 743-0445](tel:+15877430445)"
#mobile = "[(587) 743-0447](tel:+15877430447)"
mobile = "[(403) 213-5644](tel:+14032135644)"

phone = "[(403) 213-5644](tel:+14032135644)"
phone_e164format = "+14032135644"
phone_label = "(403) 213-5644"


[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# map_latitude = 50.7333
# map_longitude = -113.958
map_latitude = 50.734
map_longitude = -113.960
map_marker = "images/marker.png"


[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/DalyleDev"
title = "Twitter"
[[params.social]]
icon = "ti-github"
link = "https://github.com/dalyle"
title = "GitHub"
[[params.social]]
icon = "ti-linkedin"
link = "https://ca.linkedin.com/company/dalyle"
title = "LinkedIn"





[params.cookies]
enable = true
expire_days = 365






[params.preloader]
enable = true
preloader = "images/preloader.gif"



[params.subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=SUBSCRIBE_USER_IDd&amp;id=SUBSCRIBE_ID"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"

#
# servicedesk = Atlassian Customer Service Desk Widget
#
#
# https://dalyle.atlassian.net/jira/servicedesk/projects/CSD/settings/widget
# By embedding a lightweight request form, your customers can send requests directly from any website you control.
#
[params.servicedesk_widget]
enable = true
servicedesk_widget_html = '<script data-jsd-embedded data-key="e8082c73-3ef6-41aa-83bc-4dc17349b97f" data-base-url="https://jsd-widget.atlassian.com" src="https://jsd-widget.atlassian.com/assets/embed.js"></script>'


#
# ENGLISH
#
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2022 [Dalyle DevOps Inc.](https://www.dalyle.io/)"
home = "Home"
languageCode = "en-ca"
languageName = "en"
weight = 1


#
# ENGLISH MENU MAIN (TOP)
#

#[[Languages.en.menu.main]]
#name = "About"
#url = "about"
#weight = 1
[[Languages.en.menu.main]]
name = "Services"
url = "services"
weight = 2


# [[Languages.en.menu.main]]
# hasChildren = true
# name = "Pages"
# weight = 3
# [[Languages.en.menu.main]]
# name = "teacher"
# parent = "Pages"
# url = "teacher"
# [[Languages.en.menu.main]]
# name = "notice"
# parent = "Pages"
# url = "notice"
# [[Languages.en.menu.main]]
# name = "event"
# parent = "Pages"
# url = "event"
# [[Languages.en.menu.main]]
# name = "scholarship"
# parent = "Pages"
# url = "scholarship"
# [[Languages.en.menu.main]]
# name = "research"
# parent = "Pages"
# url = "research"


[[Languages.en.menu.main]]
name = "Blog"
url = "blog"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 5


#
# ENGLISH MENU FOOTER "Links" Section
#
# [[Languages.en.menu.footer]]
# name = "teacher"
# url = "teacher"
# [[Languages.en.menu.footer]]
# name = "notice"
# url = "notice"
# [[Languages.en.menu.footer]]
# name = "event"
# url = "event"
# [[Languages.en.menu.footer]]
# name = "scholarship"
# url = "scholarship"
# [[Languages.en.menu.footer]]
# name = "research"
# url = "research"




#
# FRENCH
#
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2022 [Dalyle DevOps Inc.](https://www.dalyle.io/)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.footer]]
name = "teacher"
url = "teacher"
[[Languages.fr.menu.footer]]
name = "notice"
url = "notice"
[[Languages.fr.menu.footer]]
name = "event"
url = "event"
[[Languages.fr.menu.footer]]
name = "scholarship"
url = "scholarship"
[[Languages.fr.menu.footer]]
name = "research"
url = "research"
[[Languages.fr.menu.main]]
name = "À propos"
url = "about"
weight = 1
[[Languages.fr.menu.main]]
name = "Cours"
url = "course"
weight = 2
[[Languages.fr.menu.main]]
hasChildren = true
name = "Pages"
weight = 3
[[Languages.fr.menu.main]]
name = "teacher"
parent = "Pages"
url = "teacher"
[[Languages.fr.menu.main]]
name = "notice"
parent = "Pages"
url = "notice"
[[Languages.fr.menu.main]]
name = "Évènement"
parent = "Pages"
url = "event"
[[Languages.fr.menu.main]]
name = "Cursus"
parent = "Pages"
url = "scholarship"
[[Languages.fr.menu.main]]
name = "research"
parent = "Pages"
url = "research"
[[Languages.fr.menu.main]]
name = "blog"
url = "blog"
weight = 4
[[Languages.fr.menu.main]]
name = "Contact"
url = "contact"
weight = 5

#
# END FRENCH
#







#
# PLUGINS
#
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#
#
#
# Allowing unsafe markup for /devops/ #gross 2022-08-08
#
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true